# Generated by Django 4.2.14 on 2024-08-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sertificates',
            new_name='Certificates',
        ),
    ]
