# Generated by Django 4.2.14 on 2024-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='time_create',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
