# Generated by Django 4.2.14 on 2024-08-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'verbose_name': 'Заявка на звонок', 'verbose_name_plural': 'Заявки на звонок'},
        ),
    ]
