# Generated by Django 4.2.14 on 2024-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_requests', '0002_alter_callrequest_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
