# Generated by Django 4.2.14 on 2024-08-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_options_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotherservice',
            options={'verbose_name': 'Другая услуга', 'verbose_name_plural': 'Другие услуги'},
        ),
        migrations.AlterModelOptions(
            name='popularservice',
            options={'verbose_name': 'Популярная услуга', 'verbose_name_plural': 'Популярные услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
    ]
