# Generated by Django 4.2.14 on 2024-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_anotherservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
