# Generated by Django 4.2.14 on 2024-08-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='another_services', to='services.service'),
        ),
        migrations.AlterField(
            model_name='popularservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular_services', to='services.service'),
        ),
    ]
