# Generated by Django 4.2.14 on 2024-08-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_anotherservice_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularservice',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AnotherService',
        ),
        migrations.DeleteModel(
            name='PopularService',
        ),
    ]
