# Generated by Django 4.2.14 on 2024-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_popularservice_service_service_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='warranty_period',
            field=models.PositiveIntegerField(),
        ),
    ]
