# Generated by Django 4.2.14 on 2024-08-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Тип устройства', 'verbose_name_plural': 'Типы устройств'},
        ),
        migrations.AlterField(
            model_name='application',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.devicetype'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'На рассмотрении'), ('P', 'В процессе работы'), ('D', 'Готов к получению')], default='C', max_length=1),
        ),
    ]
