# Generated by Django 4.2.14 on 2024-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
