# Generated by Django 4.2.14 on 2024-08-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_options_and_more'),
        ('applications', '0004_alter_application_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeeprofile'),
        ),
    ]
