# Generated by Django 4.2.14 on 2024-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default='72c9ac', editable=False, primary_key=True, serialize=False),
        ),
    ]
